name: test-action

on:
  push:
    branches:
      - test-*
    tags:
      - v*
  repository_dispatch:
    types: [test]
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout on dispatch
        if: github.event.client_payload
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: test
        env:
          GITHUB_REF_VAR: ${{ github.ref }}
          CLIENT_REF: ${{ github.event.client_payload.ref }}
        run: |
          echo ${GITHUB_REF_VAR}
          echo ${CLIENT_REF}
          echo "BRANCH="$(echo ${GITHUB_REF_VAR#refs/heads/})
          echo "BRANCH="$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV
          echo "TAG="$(echo ${GITHUB_REF_VAR#refs/tags/})
          echo "TAG="$(echo ${GITHUB_REF#refs/tags/}) >> $GITHUB_ENV
          echo "BRANCH="$(echo ${CLIENT_REF#refs/heads/})

      - name: test2
        run: |
          echo "AWS_S3_BUCKET_FULL=$([ -n $TAG ] && echo s3://hoge/fuga/$TAG || echo s3://hoge/fuga/$BRANCH/)"
          echo "AWS_S3_BUCKET_FULL=$([ -n $TAG ] && echo s3://hoge/fuga/$TAG || echo s3://hoge/fuga/$BRANCH/)" >> $GITHUB_ENV

      - name: test3
        if: github.event.client_payload && !startsWith(github.event.client_payload.ref, 'refs/tags/')
        run: |
          echo "BRANCH="$(echo ${CLIENT_REF#refs/heads/})
          echo "TAG="$(echo ${CLIENT_REF#refs/heads/}) >> $GITHUB_ENV
        env:
          CLIENT_REF: ${{ github.event.client_payload.ref }}

      - name: test4
        if: github.event.client_payload && startsWith(github.event.client_payload.ref, 'refs/tags/')
        run: |
          echo "TAG="$(echo tags/${CLIENT_REF#refs/tags/})
          echo "TAG="$(echo tags/${CLIENT_REF#refs/tags/}) >> $GITHUB_ENV
        env:
          CLIENT_REF: ${{ github.event.client_payload.ref }}
