name: test-action

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        env:
          GITHUB_REF_VAR: ${{ github.ref }}
          CLIENT_REF: ${{ github.event.client_payload.ref }}
        run: |
          echo ${GITHUB_REF_VAR}
          echo ${CLIENT_REF}
          echo "BRANCH="$(echo ${GITHUB_REF#refs/heads/})
          echo "TAG="$(echo ${GITHUB_REF#refs/tags/})
          echo "BRANCH="$(echo ${CLIENT_REF#refs/heads/})
